### ISSUE TITLE
Move unit use cases from FMI Standard to IG

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-guides#17]
There are extensive use case descriptions in the FMI Standard that are likely better suited for this guide, see 2.4.3 Physical Units.
Move only use case description, do not move all examples.

**Comment by chrbertsch** [comment]
I like this proposal

Should we then mention the implementers guide in the FMI 3 Standard (e.g. in 1.1. "What is new in FMI 3.0" or "1.4. How to Read This Document" and eplain its non-normative character?
