### ISSUE TITLE
Add MA logo to FMI implementer's guide

### ISSUE THREAD

**Issue by GallLeo** [modelica/fmi-guides#57]
Having the FMI logo and ProSTEP logo on top of the implementer's guide might lead to the impression that FMI is an ProSTEP subproject?

As the MoU (https://github.com/modelica/fmi-design/blob/master/ProSTEP/MoU_2017/2017-07-01-Memorandum-of-Understanding-MA-Prostep.pdf) is between MA (with all its MAPs) and ProSTEP, it might make sense to add the Modelica Association logo somewhere to the Implementer's Guide? (Source: https://github.com/modelica/MA-Logos).

3 logos seems a lot, but I think all organizations should be shown.
What do you think?

**Comment by pmai** [comment]
Closed via #70
