### ISSUE TITLE
Issues within fmi-ls-bus headers

### ISSUE THREAD

**Issue by ClemensB** [modelica/fmi-guides#83]
During prototyping we found some bugs within the fmi-ls-bus headers. This issue contains the fixes as well as consistency improvements.

**Comment by pmai** [comment]
Shouldn't this issue be in the fmi-ls-bus repo? I can probably transfer the issue if wanted...

**Comment by bmenne-dspace** [comment]
> Shouldn't this issue be in the fmi-ls-bus repo? I can probably transfer the issue if wanted...

@pmai We created this issue to fix the Utility headers within this guide repo. The is also one for fixing the other headers within the fmi-ls-bus repo (see https://github.com/modelica/fmi-ls-bus/issues/79). Is this OK for you?
